import Link from "next/link";
import "../styles/globals.css"

export const metadata = {
  title: "Ash Sprints",
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const header = (
    <header className="text-center bg-[conic-gradient(at_left,_var(--tw-gradient-stops))] from-sky-400 to-blue-800 p-6 my-6 rounded-md ">
      <div>
      <Link href="/">
        <h1 className="text-3xl font-bold text-white">Ash Sprints</h1>
      </Link>
      <p className="text-white">Ash sprintng through Webd🏃</p>
      </div>
  </header>
  );
  
  const footer = (
    <footer>
      <div className="border-t border-slate-800 mt-6 py-6  text-slate-600 text-center">
        <h3>Designed by Ash</h3>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <body>

        <div className="mx-auto max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
        
      </body>
    </html>
  )
}
