import Link from "next/link";
import "../styles/globals.css"

export const metadata = {
  title: "Ash's Sprints",
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const header = (
    <header className="text-center bg-[conic-gradient(at_top,_var(--tw-gradient-stops))] from-gray-900 via-gray-100 to-gray-900 p-6 my-6 rounded-md">
      <div>
      <Link href="/">
        <h1 className="text-3xl font-bold text-black">Ash Sprints</h1>
      </Link>
      <p className="text-black">Ash's sprintng through Webd🏃</p>
      </div>
  </header>
  );
  
  const footer = (
    <footer>
      <div className="border-t border-slate-800 mt-6 py-6  text-slate-600 text-center">
        <h3>Developed by Ash's trash</h3>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-indigo-300 to-purple-400">
        <div className="mx-auto max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
        
      </body>
    </html>
  )
}
